{
 "title": "EDAF Delay Decomposition Dashboard",
 "time": { "from": "now-60s", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "title": "EDAF Setup",
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/samiemostafavi/edaf/main/setup2.png\" alt=\"EDAF Setup\" style=\"height: 250px; width:550px;\"/>"
   }
  },
  {
   "title": "End-to-end Delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"packet_decomposed\" and\r\n    r._field == \"app.e2e_delay\"\r\n  )"
    }
   ]
  },
  {
   "title": "End-to-end Delay CCDF",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\n    |> range(start: -50m)\n    |> filter(fn: (r) => r._measurement == \"packet_decomposed\" and r._field == \"app.e2e_delay\" and r._value <= 400)\n    |> histogram(bins: linearBins(start: 0.0, width: 0.5, count: 800, infinity: false), normalize: true)"
    }
   ]
  },
  {
   "title": "Retransmissions Delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"packet_decomposed\" and\r\n    r._field == \"retransmission_delay\"\r\n  )"
    }
   ]
  },
  {
   "title": "E2E Avg",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\n    |> range(start: -5m)\n    |> filter(fn: (r) => r._measurement == \"packet_decomposed\" and (r._field == \"retransmission_delay\" or r._field == \"segmentation_delay\" or r._field == \"transmission_delay\" or r._field == \"queuing_delay\") )"
    }
   ]
  },
  {
   "title": "E2E > 30ms",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"packet_decomposed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r[\"app.e2e_delay\"] > 30.0)"
    }
   ]
  },
  {
   "title": "Segmentation Delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"packet_decomposed\" and\r\n    r._field == \"segmentation_delay\"\r\n  )"
    }
   ]
  },
  {
   "title": "Transmission Delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"packet_decomposed\" and\r\n    r._field == \"transmission_delay\"\r\n  )"
    }
   ]
  },
  {
   "title": "Queueing Delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"edaf_main\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"packet_decomposed\" and\r\n    r._field == \"queuing_delay\"\r\n  )"
    }
   ]
  }
 ]
}